### ISSUE TITLE
Add The Tag In every page head Section

### ISSUE THREAD

**Issue by dkkaran1996** [vac-soft/vacsoftteck#43]
### Kindly place the below code in Website after head section of each page in VAC Softteck Website.

`<!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=G-EKTLZCJV6J&quot;></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-EKTLZCJV6J'); </script>`

**Comment by Srinivasan260** [comment]
#44  done updated google analysis
