### ISSUE TITLE
Add UPI Payments in Website

### ISSUE THREAD

**Issue by dkkaran1996** [vac-soft/vacsoftteck#46]
Hi @Srinivasan260 ,

Add a Button in Webpage to open a popup to show

UPI Payment and Other Payments.
For UPI Payments QR code will be shown,
For Other Payments Razorpay Button Need to show.

**Comment by Srinivasan260** [comment]
Sir...Added a Button in Webpage to open a popup to show

UPI Payment and Other Payments.
For UPI Payments QR code will be show
For Other Payments Razorpay Button  will be show

Code Pushed to Github Repository vacsoftteck (srini Branch)
