### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by soundharya-9629** [vac-soft/vacsoftteck#58]
In Footer Field Add another Icon for Twitter.

**Comment by dkkaran1996** [comment]
@Srinivasan260 

In Twitter icon, you shoulkd not add icon only, Yiu have to add the twitter link also.

**Comment by Srinivasan260** [comment]
Sir ...Please check one more time.. I addded the link also in Twitter Icon 
<a target="_blank" href="https://twitter.com/VSoftteck?t=CWuoQepTnAXEYLbBYsBc_w&s=09" class="twitter" aria-label="Visit our Twitter account page"><i class="bi bi-twitter"></i></a>
